/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsSlugRouteImport } from './routes/jobs/$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicGuestChatRouteImport } from './routes/api/public/guest-chat'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminPromptsRouteImport } from './routes/_authenticated/admin.prompts'
import { Route as ApiPublicJobsSlugRouteImport } from './routes/api/public/jobs/$slug'
import { Route as ApiPublicApolloPhoneRouteImport } from './routes/api/public/apollo/phone'
import { Route as AuthenticatedOauthGoogleReturnRouteImport } from './routes/_authenticated/oauth.google.return'
import { Route as AuthenticatedAppCIdRouteImport } from './routes/_authenticated/app.c.$id'
import { Route as ApiPublicJobsSlugChatRouteImport } from './routes/api/public/jobs/$slug/chat'
import { Route as ApiPublicJobsSlugApplyRouteImport } from './routes/api/public/jobs/$slug/apply'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicGuestChatRoute = ApiPublicGuestChatRouteImport.update({
  id: '/api/public/guest-chat',
  path: '/api/public/guest-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPromptsRoute =
  AuthenticatedAdminPromptsRouteImport.update({
    id: '/admin/prompts',
    path: '/admin/prompts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicJobsSlugRoute = ApiPublicJobsSlugRouteImport.update({
  id: '/api/public/jobs/$slug',
  path: '/api/public/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApolloPhoneRoute = ApiPublicApolloPhoneRouteImport.update({
  id: '/api/public/apollo/phone',
  path: '/api/public/apollo/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOauthGoogleReturnRoute =
  AuthenticatedOauthGoogleReturnRouteImport.update({
    id: '/oauth/google/return',
    path: '/oauth/google/return',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCIdRoute = AuthenticatedAppCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicJobsSlugChatRoute = ApiPublicJobsSlugChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ApiPublicJobsSlugRoute,
} as any)
const ApiPublicJobsSlugApplyRoute = ApiPublicJobsSlugApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ApiPublicJobsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/api/public/guest-chat': typeof ApiPublicGuestChatRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/c/$id': typeof AuthenticatedAppCIdRoute
  '/oauth/google/return': typeof AuthenticatedOauthGoogleReturnRoute
  '/api/public/apollo/phone': typeof ApiPublicApolloPhoneRoute
  '/api/public/jobs/$slug': typeof ApiPublicJobsSlugRouteWithChildren
  '/api/public/jobs/$slug/apply': typeof ApiPublicJobsSlugApplyRoute
  '/api/public/jobs/$slug/chat': typeof ApiPublicJobsSlugChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/api/public/guest-chat': typeof ApiPublicGuestChatRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/c/$id': typeof AuthenticatedAppCIdRoute
  '/oauth/google/return': typeof AuthenticatedOauthGoogleReturnRoute
  '/api/public/apollo/phone': typeof ApiPublicApolloPhoneRoute
  '/api/public/jobs/$slug': typeof ApiPublicJobsSlugRouteWithChildren
  '/api/public/jobs/$slug/apply': typeof ApiPublicJobsSlugApplyRoute
  '/api/public/jobs/$slug/chat': typeof ApiPublicJobsSlugChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/_authenticated/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/api/public/guest-chat': typeof ApiPublicGuestChatRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/c/$id': typeof AuthenticatedAppCIdRoute
  '/_authenticated/oauth/google/return': typeof AuthenticatedOauthGoogleReturnRoute
  '/api/public/apollo/phone': typeof ApiPublicApolloPhoneRoute
  '/api/public/jobs/$slug': typeof ApiPublicJobsSlugRouteWithChildren
  '/api/public/jobs/$slug/apply': typeof ApiPublicJobsSlugApplyRoute
  '/api/public/jobs/$slug/chat': typeof ApiPublicJobsSlugChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app'
    | '/api/chat'
    | '/jobs/$slug'
    | '/admin/prompts'
    | '/admin/usage'
    | '/api/public/guest-chat'
    | '/app/'
    | '/app/c/$id'
    | '/oauth/google/return'
    | '/api/public/apollo/phone'
    | '/api/public/jobs/$slug'
    | '/api/public/jobs/$slug/apply'
    | '/api/public/jobs/$slug/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/chat'
    | '/jobs/$slug'
    | '/admin/prompts'
    | '/admin/usage'
    | '/api/public/guest-chat'
    | '/app'
    | '/app/c/$id'
    | '/oauth/google/return'
    | '/api/public/apollo/phone'
    | '/api/public/jobs/$slug'
    | '/api/public/jobs/$slug/apply'
    | '/api/public/jobs/$slug/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/app'
    | '/api/chat'
    | '/jobs/$slug'
    | '/_authenticated/admin/prompts'
    | '/_authenticated/admin/usage'
    | '/api/public/guest-chat'
    | '/_authenticated/app/'
    | '/_authenticated/app/c/$id'
    | '/_authenticated/oauth/google/return'
    | '/api/public/apollo/phone'
    | '/api/public/jobs/$slug'
    | '/api/public/jobs/$slug/apply'
    | '/api/public/jobs/$slug/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  JobsSlugRoute: typeof JobsSlugRoute
  ApiPublicGuestChatRoute: typeof ApiPublicGuestChatRoute
  ApiPublicApolloPhoneRoute: typeof ApiPublicApolloPhoneRoute
  ApiPublicJobsSlugRoute: typeof ApiPublicJobsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/guest-chat': {
      id: '/api/public/guest-chat'
      path: '/api/public/guest-chat'
      fullPath: '/api/public/guest-chat'
      preLoaderRoute: typeof ApiPublicGuestChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/prompts': {
      id: '/_authenticated/admin/prompts'
      path: '/admin/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AuthenticatedAdminPromptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/jobs/$slug': {
      id: '/api/public/jobs/$slug'
      path: '/api/public/jobs/$slug'
      fullPath: '/api/public/jobs/$slug'
      preLoaderRoute: typeof ApiPublicJobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apollo/phone': {
      id: '/api/public/apollo/phone'
      path: '/api/public/apollo/phone'
      fullPath: '/api/public/apollo/phone'
      preLoaderRoute: typeof ApiPublicApolloPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/oauth/google/return': {
      id: '/_authenticated/oauth/google/return'
      path: '/oauth/google/return'
      fullPath: '/oauth/google/return'
      preLoaderRoute: typeof AuthenticatedOauthGoogleReturnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/c/$id': {
      id: '/_authenticated/app/c/$id'
      path: '/c/$id'
      fullPath: '/app/c/$id'
      preLoaderRoute: typeof AuthenticatedAppCIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/jobs/$slug/chat': {
      id: '/api/public/jobs/$slug/chat'
      path: '/chat'
      fullPath: '/api/public/jobs/$slug/chat'
      preLoaderRoute: typeof ApiPublicJobsSlugChatRouteImport
      parentRoute: typeof ApiPublicJobsSlugRoute
    }
    '/api/public/jobs/$slug/apply': {
      id: '/api/public/jobs/$slug/apply'
      path: '/apply'
      fullPath: '/api/public/jobs/$slug/apply'
      preLoaderRoute: typeof ApiPublicJobsSlugApplyRouteImport
      parentRoute: typeof ApiPublicJobsSlugRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCIdRoute: typeof AuthenticatedAppCIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCIdRoute: AuthenticatedAppCIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedAdminPromptsRoute: typeof AuthenticatedAdminPromptsRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedOauthGoogleReturnRoute: typeof AuthenticatedOauthGoogleReturnRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedAdminPromptsRoute: AuthenticatedAdminPromptsRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedOauthGoogleReturnRoute: AuthenticatedOauthGoogleReturnRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicJobsSlugRouteChildren {
  ApiPublicJobsSlugApplyRoute: typeof ApiPublicJobsSlugApplyRoute
  ApiPublicJobsSlugChatRoute: typeof ApiPublicJobsSlugChatRoute
}

const ApiPublicJobsSlugRouteChildren: ApiPublicJobsSlugRouteChildren = {
  ApiPublicJobsSlugApplyRoute: ApiPublicJobsSlugApplyRoute,
  ApiPublicJobsSlugChatRoute: ApiPublicJobsSlugChatRoute,
}

const ApiPublicJobsSlugRouteWithChildren =
  ApiPublicJobsSlugRoute._addFileChildren(ApiPublicJobsSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  JobsSlugRoute: JobsSlugRoute,
  ApiPublicGuestChatRoute: ApiPublicGuestChatRoute,
  ApiPublicApolloPhoneRoute: ApiPublicApolloPhoneRoute,
  ApiPublicJobsSlugRoute: ApiPublicJobsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
